### PR TITLE
Add website with YouTube feed

### PR DESCRIPTION
**Pull request by ghost**
I've created a basic website that fetches videos from the YouTube channels listed in this repo and displays them in a single feed.

image

Can we quickly deploy this to https://manimcommunity.github.io/awesome-manim so that I can check if it works? (i.e. the Jekyll site under `/frontend`)

- Storage on Supabase free tier
- Backend hosted on Google App Engine
- Frontend that uses jQuery and Jekyll hosted on GH pages

Remaining tasks:

- [x] Handle custom channel URLs
- [x] Set up cron job to scrape every 24 hours on GAE
- [x] Add spinner
- [ ] Cosmetic stuff

Feel free to suggest new features/feedback

### CODE REVIEW

**Comment by naveen521kk** [comment]
Thanks for your work here!

I think this would be better under the main site, ie say at `https://manim.community/awesome-manim`. Also, having it under the main site means the design can be re-used. That site uses [Gatsby](https://www.gatsbyjs.com/) where JSX can be used instead of direct HTML (much better than doing [this](https://github.com/ManimCommunity/awesome-manim/pull/14/files#diff-959f9cada636604db33bc1ba82fed347457dcb032c37ac195b4343c5f0ea6e72R27-R45)). Also, for the maintainers, the number of sites to maintain would be less (already we have [home-page](https://manim.community), [plugins-site](https://plugins.manim.community), [timezone-site](https://timezone.manim.community), [try-manim](https://try.manim.community)).

Also, I would like to have a section on the [homepage](https://manim.community), like say "Made with Manim". What do you think about this?

**Comment by prism0x** [comment]
> That site uses [Gatsby](https://www.gatsbyjs.com/) where JSX can be used instead of direct HTML (much better than doing [this](https://github.com/ManimCommunity/awesome-manim/pull/14/files#diff-959f9cada636604db33bc1ba82fed347457dcb032c37ac195b4343c5f0ea6e72R27-R45)).

Ok, I could try to port this to the main website repo with Gatsby. Let me know if you'd like me to start doing that, cc @behackl.

Are you satisfied with the backend? The API is simple enough (just a JSON array of objects) so that any curation we might introduce to the videos later on would work seamlessly without us having to modify the frontend.

> Also, I would like to have a section on the [homepage](https://manim.community/), like say "Made with Manim". What do you think about this?

Yes, that was my idea too, alongside a standalone page. How do you imagine it specifically for the one on the homepage? A caroussel of YouTube videos, one at a time? Or e.g. a section with 3 videos (with high views) side by side, with a link that says "see more videos made with Manim"? Open to any idea.

cc @naveen521kk

**Comment by naveen521kk** [comment]
> Ok, I could try to port this to the main website repo with Gatsby. Let me know if you'd like me to start doing that

If you want you can start doing, PR's welcome!

> Are you satisfied with the backend? The API is simple enough (just a JSON array of objects) so that any curation we might introduce to the videos later on would work seamlessly without us having to modify the frontend.

SGTM. I haven't checked/tested the code for that but the idea looks good. Also, we do have access to Oracle Cloud (we got it through their ARM plan, I think) and we can use it if needed.

> Yes, that was my idea too, alongside a standalone page. How do you imagine it specifically for the one on the homepage? A caroussel of YouTube videos, one at a time? Or e.g. a section with 3 videos (with high views) side by side, with a link that says "see more videos made with Manim"? Open to any idea.

A carousel of YouTube videos one at a time looks good to me, though that's just my personal preference. The carousel should have a limited number of videos (say 3) and there should be a link for the other page that say "see more videos made with Manim".

**Comment by prism0x** [comment]
Closing this PR since this work is being continued in other repos:

- https://github.com/ManimCommunity/manim-website/pull/73
- https://github.com/manimCommunity/manim-website-api

**Pull request closed without merging**
